"""Ajustado os relacionamentos de models

Revision ID: 10859941e427
Revises: 53497e926c28
Create Date: 2024-05-15 14:56:27.317981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10859941e427"
down_revision: Union[str, None] = "53497e926c28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=True),
        sa.Column("senha", sa.String(), nullable=True),
        sa.Column("telefone", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usuario_id"), ["id"], unique=False)

    with op.batch_alter_table("produto", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fk_usuario", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_produto_id"), ["id"], unique=False)
        batch_op.create_foreign_key("fk_usuario", "usuario", ["fk_usuario"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("produto", schema=None) as batch_op:
        batch_op.drop_constraint("fk_usuario", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_produto_id"))
        batch_op.drop_column("fk_usuario")

    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usuario_id"))

    op.drop_table("usuario")
    # ### end Alembic commands ###
